# Generated by Django 6.0.7 on 2026-07-29 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Día de Piernas, Rutina Torso', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles opcionales de la rutina')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('etiqueta', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='rutinas.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(blank=True, help_text='¿Este registro formó parte de una rutina específica?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='rutinas.rutina')),
            ],
            options={
                'verbose_name': 'Registro de Ejercicio',
                'verbose_name_plural': 'Registros de Ejercicios',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden en el que se realiza el ejercicio')),
                ('series_objetivo', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('repeticiones_objetivo', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('rutina', 'ejercicio')},
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='rutinas', through='rutinas.RutinaEjercicio', to='rutinas.ejercicio'),
        ),
    ]
