# Generated by Django 6.0.7 on 2026-07-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0005_registroejercicio_creado_en'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio'),
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='rutinas', through='rutinas.RutinaEjercicio', to='ejercicios.ejercicio'),
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='RegistroEjercicio',
        ),
    ]
