# Generated by Django 6.0.7 on 2026-09-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_alter_rutinaejercicio_ejercicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='tiempo_objetivo_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo objetivo en segundos (ej. 45 para plancha)', null=True),
        ),
    ]
