# Generated by Django 6.0.7 on 2026-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_rutinaejercicio_tiempo_objetivo_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Códigos numéricos de los días de la semana separados por comas (0=Lun, ..., 6=Dom)', max_length=50, verbose_name='Días asignados'),
        ),
    ]
