# Generated by Django 6.0.7 on 2026-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_rutina_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='peso_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carga en kg planificada para este ejercicio (dejar en blanco para peso corporal o libre)', max_digits=5, null=True, verbose_name='Peso objetivo (kg)'),
        ),
    ]
