# Generated by Django 6.0.7 on 2026-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_rutinaejercicio_peso_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='distancia_objetivo_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia planificada en km (ej. 5.0 para carrera)', max_digits=6, null=True, verbose_name='Distancia objetivo (km)'),
        ),
    ]
