# Generated by Django 6.0.7 on 2026-07-26 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, help_text='Altura en cm', null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('PR', 'Principiante'), ('IN', 'Intermedio'), ('AV', 'Avanzado')], default='PR', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
