# Generated by Django 6.0.7 on 2026-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/'),
        ),
    ]
