# Generated by Django 6.0.7 on 2026-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biografia',
            field=models.CharField(blank=True, default='', help_text='Una breve frase motivadora o descripción personal', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='dias_objetivo_semana',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Días objetivo por semana'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_fin_suscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de Suscripción'),
        ),
        migrations.AddField(
            model_name='profile',
            name='objetivo',
            field=models.CharField(choices=[('HIP', 'Hipertrofia / Ganar Músculo'), ('DEF', 'Definición / Perder Grasa'), ('FUE', 'Fuerza / Rendimiento'), ('SAL', 'Salud y Condición Física'), ('RES', 'Resistencia y Cardio')], default='HIP', max_length=3, verbose_name='Objetivo Principal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_suscripcion',
            field=models.CharField(choices=[('FREE', 'Plan Gratuito'), ('PRO', 'FitApp PRO ⭐'), ('COACH', 'Coach / Entrenador')], default='FREE', max_length=10, verbose_name='Plan de Suscripción'),
        ),
    ]
