# Generated by Django 6.0.7 on 2026-09-19 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_biografia_profile_dias_objetivo_semana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error / Excepción'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10, verbose_name='Nivel')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAIL', 'Intento de login fallido'), ('REGISTRO', 'Registro de nuevo usuario'), ('PERFIL_EDIT', 'Edición de perfil'), ('PASSWORD_RESET', 'Solicitud reseteo de clave'), ('PASSWORD_CHANGE', 'Cambio de clave'), ('RUTINA_CREATE', 'Creación de rutina'), ('SERIE_LOG', 'Registro de serie en Modo Gym'), ('ERROR_500', 'Excepción 500 en servidor'), ('OTRO', 'Otro evento')], default='INFO', max_length=20, verbose_name='Tipo de Evento')),
                ('ruta', models.CharField(blank=True, default='', max_length=255, verbose_name='Ruta / URL')),
                ('metodo', models.CharField(blank=True, default='GET', max_length=10, verbose_name='Método HTTP')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='Dispositivo / Navegador')),
                ('mensaje', models.TextField(verbose_name='Mensaje o Descripción')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traza de Error (Traceback)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_actividad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Auditoría de Actividad e Incidencias',
                'ordering': ['-creado_en'],
            },
        ),
    ]
