# Generated by Django 6.0.7 on 2026-09-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha confirmado su dirección de correo electrónico mediante el enlace de activación', verbose_name='Email Verificado'),
        ),
    ]
