# Generated by Django 6.0.7 on 2026-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='tipo',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAIL', 'Intento de login fallido'), ('REGISTRO', 'Registro de nuevo usuario'), ('PERFIL_EDIT', 'Edición de perfil'), ('PASSWORD_RESET', 'Solicitud reseteo de clave'), ('PASSWORD_CHANGE', 'Cambio de clave'), ('RUTINA_CREATE', 'Creación de rutina'), ('SERIE_LOG', 'Registro de serie en Modo Gym'), ('ERROR_500', 'Excepción 500 en servidor'), ('OTRO', 'Otro evento')], default='OTRO', max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
