# Generated by Django 6.0.7 on 2026-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_logactividad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro / Prefiero no decir')], help_text='Permite adaptar recomendaciones de salud, métricas y entrenamiento', max_length=1, null=True, verbose_name='Sexo / Género'),
        ),
    ]
