# Generated by Django 6.0.7 on 2026-09-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_mantenimiento', models.BooleanField(default=False, help_text='Si está activo, los visitantes y usuarios normales verán la pantalla de mantenimiento (503). Solo Staff y Administradores podrán acceder.', verbose_name='Modo Mantenimiento Activo')),
                ('mensaje_mantenimiento', models.TextField(default='Estamos realizando labores de optimización y mantenimiento en FitApp. Estaremos de vuelta muy pronto.', help_text='Texto explicativo mostrado a los usuarios en la pantalla 503.', verbose_name='Mensaje de Mantenimiento')),
                ('tiempo_estimado_reapertura', models.CharField(blank=True, help_text="Ejemplo: 'En 30 minutos', 'Hoy a las 18:00 h'", max_length=100, verbose_name='Tiempo Estimado de Reapertura')),
                ('registro_abierto', models.BooleanField(default=True, help_text='Si se desactiva, nadie podrá crear nuevas cuentas por el formulario público.', verbose_name='Registro Público Abierto')),
                ('mensaje_registro_cerrado', models.TextField(default='El registro de nuevos usuarios se encuentra temporalmente cerrado. Contacta con la administración para solicitar una cuenta.', help_text='Mensaje informativo cuando un usuario intenta acceder al registro estando cerrado.', verbose_name='Mensaje de Registro Cerrado')),
                ('banner_activo', models.BooleanField(default=False, help_text='Muestra una barra de notificación superior fija para todos los usuarios autenticados.', verbose_name='Banner Global Activo')),
                ('banner_texto', models.CharField(blank=True, help_text="Aviso breve (ej. '¡Actualización importante: nuevo sistema de cálculo 1RM disponible!').", max_length=255, verbose_name='Texto del Banner')),
                ('banner_tipo', models.CharField(choices=[('INFO', 'Información (Azul)'), ('WARNING', 'Advertencia (Ámbar)'), ('SUCCESS', 'Éxito (Esmeralda)'), ('DANGER', 'Urgente (Rojo)')], default='INFO', max_length=20, verbose_name='Tipo de Banner')),
                ('usuarios_pueden_crear_ejercicios', models.BooleanField(default=True, help_text='Si se desactiva, los usuarios normales solo podrán usar los ejercicios del catálogo oficial.', verbose_name='Permitir a Usuarios Crear Ejercicios')),
                ('nombre_sitio', models.CharField(default='FitApp', max_length=100, verbose_name='Nombre de la Plataforma')),
                ('email_soporte', models.EmailField(blank=True, default='soporte@fitapp.com', max_length=100, verbose_name='Email de Soporte')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
