# Generated by Django 6.0.7 on 2026-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email_soporte',
            field=models.EmailField(blank=True, default='soporte@optifit.es', max_length=100, verbose_name='Email de Soporte'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_sitio',
            field=models.CharField(default='OptiFitApp', max_length=100, verbose_name='Nombre de la Plataforma'),
        ),
    ]
