"""
Catálogo oficial de ejercicios predeterminados para FitApp.
Contiene las máquinas más importantes de gimnasio, calistenia, cinta, running exterior,
bicicleta, peso libre esencial, deportes y movilidad.
"""

CATALOGO_EJERCICIOS = [
    # =========================================================================
    # A. MÁQUINAS MÁS IMPORTANTES DE GIMNASIO (TIPO: 'MAQ')
    # =========================================================================
    {
        'nombre': 'Prensa de Piernas (Leg Press)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de prensa de piernas (a 45° o horizontal)',
        'definicion': 'Prensa con plataforma guiada para empuje de piernas. Permite trabajar cuádriceps, glúteos e isquiotibiales con gran seguridad y soporte lumbar.',
    },
    {
        'nombre': 'Extensión de Cuádriceps (Leg Extension)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de extensiones de piernas',
        'definicion': 'Aislamiento sentado para la cara anterior del muslo. Extender las piernas de forma fluida y controlar la bajada excéntrica sin bloquear violentamente las rodillas.',
    },
    {
        'nombre': 'Curl Femoral Sentado / Tumbado (Leg Curl)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de curl femoral sentado o tumbado',
        'definicion': 'Flexión de rodillas contra rodillo acolchado para aislar los isquiotibiales y la musculatura flexora posterior de la pierna.',
    },
    {
        'nombre': 'Press de Pecho en Máquina (Chest Press)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de press horizontal sentado',
        'definicion': 'Empuje horizontal guiado para el desarrollo seguro del pectoral mayor, tríceps y deltoides anterior, excelente para sobrecarga progresiva estable.',
    },
    {
        'nombre': 'Contractora de Pecho / Pec Deck (Aperturas)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina contractora / Pec Deck',
        'definicion': 'Aducción de brazos con codos semi-flexionados para aislar y concentrar la tensión en la porción media y esternal del pectoral.',
    },
    {
        'nombre': 'Jalón al Pecho en Polea (Lat Pulldown)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'ESP',
        'dificultad': 'PRI',
        'equipo_necesario': 'Torre de polea alta con barra larga',
        'definicion': 'Tracción vertical hacia la parte superior del pecho con retracción escapular, desarrollando amplitud de dorsales y fuerza en bíceps.',
    },
    {
        'nombre': 'Remo en Polea Baja / Gironda (Seated Cable Row)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'ESP',
        'dificultad': 'PRI',
        'equipo_necesario': 'Torre de polea baja con maneral en V',
        'definicion': 'Tracción horizontal sentado dirigiendo el agarre hacia el ombligo para ganar densidad de espalda media, romboides y trapecios.',
    },
    {
        'nombre': 'Press de Hombros en Máquina (Shoulder Press)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'HOM',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de press militar guiado',
        'definicion': 'Empuje vertical sentado con agarre neutro o prono, aislando el deltoides anterior y lateral con mínimo estrés lumbar.',
    },
    {
        'nombre': 'Elevaciones Laterales en Máquina',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'HOM',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de elevaciones laterales para hombro',
        'definicion': 'Elevación guiada de brazos contra almohadillas que mantiene tensión continua en el deltoides lateral a lo largo de todo el movimiento.',
    },
    {
        'nombre': 'Extensión de Tríceps en Polea (Triceps Pushdown)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'BRA',
        'dificultad': 'PRI',
        'equipo_necesario': 'Polea alta con cuerda o barra recta',
        'definicion': 'Extensión de codo hacia abajo manteniendo los codos fijados a los costados del torso, incidiendo en las tres cabezas del tríceps.',
    },
    {
        'nombre': 'Curl de Bíceps en Polea / Máquina Scott',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'BRA',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina banco Scott o polea baja',
        'definicion': 'Flexión de codo con soporte inclinado para evitar el balanceo corporal y maximizar el aislamiento del bíceps braquial.',
    },
    {
        'nombre': 'Máquina de Abductores (Apertura de Cadera)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'GLU',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de abductores sentado',
        'definicion': 'Apertura lateral de piernas sentado para activar y fortalecer glúteo medio, glúteo menor y estabilizadores pélvicos.',
    },
    {
        'nombre': 'Máquina de Aductores (Cierre de Cadera)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de aductores sentado',
        'definicion': 'Cierre controlado de piernas hacia la línea media, fortaleciendo la musculatura aductora de la cara interna del muslo.',
    },
    {
        'nombre': 'Elevación de Gemelos en Máquina',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina de gemelos de pie o sentado',
        'definicion': 'Extensión y flexión plantar de tobillos con pausa isométrica arriba para el desarrollo completo de gemelos (gastrocnemio) y sóleo.',
    },
    {
        'nombre': 'Hip Thrust en Máquina / Multipower',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'GLU',
        'dificultad': 'INT',
        'equipo_necesario': 'Máquina específica de Hip Thrust o barra Multipower con almohadilla',
        'definicion': 'Empuje de cadera con apoyo de escápulas, considerado el ejercicio de mayor activación y carga para el glúteo mayor.',
    },
    {
        'nombre': 'Cruces de Poleas (Cable Crossover)',
        'tipo': 'MAQ',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'INT',
        'equipo_necesario': 'Torre de doble polea regulable',
        'definicion': 'Aducción de brazos cruzando los cables por delante del pecho para un bombeo y congestión muscular extrema.',
    },

    # =========================================================================
    # B. CALISTENIA Y PESO CORPORAL (TIPO: 'CAL')
    # =========================================================================
    {
        'nombre': 'Dominadas Pronas (Pull-ups)',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'ESP',
        'dificultad': 'INT',
        'equipo_necesario': 'Barra fija de dominadas',
        'definicion': 'Tracción vertical con agarre prono más ancho que los hombros hasta superar la barra con la barbilla. Rey de la calistenia para espalda.',
    },
    {
        'nombre': 'Dominadas Supinas (Chin-ups)',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'ESP',
        'dificultad': 'INT',
        'equipo_necesario': 'Barra fija de dominadas',
        'definicion': 'Tracción vertical con palmas hacia el rostro. Gran demanda combinada de dorsales y flexores de brazos (bíceps).',
    },
    {
        'nombre': 'Fondos en Paralelas (Dips)',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'INT',
        'equipo_necesario': 'Barras paralelas o estación de fondos',
        'definicion': 'Descenso y empuje del peso corporal en paralelas para hipertrofia y fuerza en tríceps, pectoral inferior y deltoides.',
    },
    {
        'nombre': 'Flexiones de Pecho (Push-ups)',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'PRI',
        'equipo_necesario': 'Suelo / Esterilla',
        'definicion': 'Empuje horizontal en el suelo con alineación recta de columna y core activo, rozando el suelo con el pecho en cada repetición.',
    },
    {
        'nombre': 'Plancha Abdominal Isométrica (Plank)',
        'tipo': 'CAL',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'COR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Esterilla',
        'definicion': 'Sostén isométrico sobre antebrazos y puntas de los pies contrayendo abdomen, glúteos y cuádriceps de forma ininterrumpida.',
    },
    {
        'nombre': 'Plancha Lateral',
        'tipo': 'CAL',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'COR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Esterilla',
        'definicion': 'Apoyo lateral sobre un único antebrazo elevando la pelvis para activar oblicuos y estabilizar la faja lumbo-abdominal.',
    },
    {
        'nombre': 'Elevaciones de Piernas Colgado',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'COR',
        'dificultad': 'INT',
        'equipo_necesario': 'Barra de dominadas',
        'definicion': 'Elevación controlada de piernas rectas o rodillas hacia el pecho suspendido en barra, incidiendo en el recto abdominal y flexores de cadera.',
    },
    {
        'nombre': 'Abdominales Crunch en Suelo',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'COR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Esterilla',
        'definicion': 'Flexión de la columna torácica despegando las escápulas del suelo sin forzar la nuca, apretando el abdomen en la parte alta.',
    },
    {
        'nombre': 'Sentadillas Aéreas (Air Squats)',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Ninguno',
        'definicion': 'Sentadillas profundas sin carga externa para perfeccionar el patrón de movilidad de cadera y rodillas.',
    },
    {
        'nombre': 'Fondos de Tríceps en Banco',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'BRA',
        'dificultad': 'PRI',
        'equipo_necesario': 'Banco plano o silla estable',
        'definicion': 'Manos apoyadas al borde del banco con piernas adelantadas, flexionando los codos a 90 grados para trabajar los tríceps con peso corporal.',
    },
    {
        'nombre': 'Muscle-up en Barra',
        'tipo': 'CAL',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'FUL',
        'dificultad': 'AVA',
        'equipo_necesario': 'Barra fija de calistenia',
        'definicion': 'Movimiento calisténico avanzado de potencia que une una tracción vertical explosiva con la transición y fondo por encima de la barra.',
    },

    # =========================================================================
    # C. CARDIO, CINTA, BICICLETA Y AIRE LIBRE (TIPO: 'CAR' y 'OUT')
    # =========================================================================
    {
        'nombre': 'Correr en Cinta (Treadmill Running)',
        'tipo': 'CAR',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Cinta de correr',
        'definicion': 'Carrera continua o series de intervalos en cinta rodante de gimnasio. Permite controlar la velocidad, el ritmo y la pendiente con absorción de impacto.',
    },
    {
        'nombre': 'Correr al Aire Libre (Outdoor Running)',
        'tipo': 'OUT',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Zapatillas de running',
        'definicion': 'Carrera continua o cambios de ritmo en exterior (parques, asfalto o caminos). Mejora la resistencia aeróbica, la capacidad pulmonar y la salud cardiovascular.',
    },
    {
        'nombre': 'Bicicleta Estática / Ciclo Indoor (Spinning)',
        'tipo': 'CAR',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Bicicleta estática o ciclo indoor',
        'definicion': 'Sesión de pedaleo continuo o por intervalos con resistencia graduable. Excelente quema calórica protegiendo las rodillas y articulaciones del impacto.',
    },
    {
        'nombre': 'Ciclismo al Aire Libre',
        'tipo': 'OUT',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Bicicleta y casco',
        'definicion': 'Ruta en bicicleta en exterior (carretera, pista o montaña). Gran estímulo de fondo cardiovascular, fortalecimiento de piernas y desconexión mental.',
    },
    {
        'nombre': 'Elíptica',
        'tipo': 'CAR',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Máquina elíptica',
        'definicion': 'Ejercicio aeróbico guiado que sincroniza empuje/tracción de brazos con pedaleo elíptico continuo sin impacto contra el suelo.',
    },
    {
        'nombre': 'Remo Ergómetro (Indoor Rower)',
        'tipo': 'CAR',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'INT',
        'equipo_necesario': 'Máquina de remo Concept2 o similar',
        'definicion': 'Ejercicio cardiovascular integral de empuje con piernas y tracción con tronco y brazos, con elevadísimo gasto calórico y potencia respiratoria.',
    },
    {
        'nombre': 'Escaladora (Stairmaster)',
        'tipo': 'CAR',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'INT',
        'equipo_necesario': 'Máquina de escaleras / Stairmaster',
        'definicion': 'Subida continua de peldaños giratorios que exige alta resistencia cardíaca y focaliza el trabajo en glúteos, cuádriceps y gemelos.',
    },
    {
        'nombre': 'Salto a la Comba',
        'tipo': 'CAR',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Cuerda de saltar',
        'definicion': 'Saltos rítmicos sobre cuerda para agilidad, coordinación, velocidad de pies y condicionamiento metabólico intenso.',
    },
    {
        'nombre': 'Caminata / Senderismo (Hiking)',
        'tipo': 'OUT',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'CAR',
        'dificultad': 'PRI',
        'equipo_necesario': 'Calzado cómodo o de senderismo',
        'definicion': 'Caminata a ritmo constante por senderos naturales o entorno urbano, ideal para acumular pasos, salud metabólica y recuperación activa.',
    },

    # =========================================================================
    # D. PESO LIBRE FUNDAMENTAL (TIPO: 'LIB')
    # =========================================================================
    {
        'nombre': 'Press de Banca Plano con Barra',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'INT',
        'equipo_necesario': 'Banco plano, barra olímpica y discos',
        'definicion': 'El ejercicio básico imprescindible de fuerza para pectoral, tríceps y deltoides anterior con barra en banco plano.',
    },
    {
        'nombre': 'Press Inclinado con Mancuernas',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PEC',
        'dificultad': 'INT',
        'equipo_necesario': 'Banco regulable a 30°-45° y mancuernas',
        'definicion': 'Empuje con mancuernas en banco inclinado, excelente para priorizar el haz clavicular superior del pectoral con mayor rango de recorrido.',
    },
    {
        'nombre': 'Sentadilla Trasera con Barra (Back Squat)',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'INT',
        'equipo_necesario': 'Rack de sentadillas, barra olímpica y discos',
        'definicion': 'Patrón fundamental de flexión de rodilla y cadera cargando la barra sobre los trapecios. Fuerza pura para piernas, glúteos y tronco.',
    },
    {
        'nombre': 'Peso Muerto Convencional (Deadlift)',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'ESP',
        'dificultad': 'INT',
        'equipo_necesario': 'Barra olímpica y discos',
        'definicion': 'Levantamiento de barra desde el suelo mediante bisagra de cadera. Fortalece toda la cadena posterior: erectores espinales, glúteos, isquios y trapecios.',
    },
    {
        'nombre': 'Peso Muerto Rumano con Mancuernas',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'INT',
        'equipo_necesario': 'Mancuernas',
        'definicion': 'Bisagra de cadera con rodillas semi-flexionadas descendiendo las mancuernas pegadas a las piernas para estirar y fortalecer isquiotibiales y glúteos.',
    },
    {
        'nombre': 'Press Militar de Hombros',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'HOM',
        'dificultad': 'INT',
        'equipo_necesario': 'Barra o mancuernas',
        'definicion': 'Empuje vertical por encima de la cabeza de pie o sentado, construyendo deltoides redondeados, trapecios y estabilidad del core.',
    },
    {
        'nombre': 'Remo con Mancuerna a una Mano',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'ESP',
        'dificultad': 'PRI',
        'equipo_necesario': 'Banco plano y mancuerna',
        'definicion': 'Tracción unilateral con rodilla y mano apoyadas en banco, dirigiendo el codo hacia la cadera para aislar el dorsal ancho.',
    },
    {
        'nombre': 'Curl de Bíceps con Mancuernas',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'BRA',
        'dificultad': 'PRI',
        'equipo_necesario': 'Mancuernas',
        'definicion': 'Flexión de brazos alterna o simultánea con supinación de muñeca para el desarrollo de la masa y pico del bíceps.',
    },
    {
        'nombre': 'Press Francés para Tríceps',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'BRA',
        'dificultad': 'INT',
        'equipo_necesario': 'Banco plano y barra Z o mancuernas',
        'definicion': 'Extensión de codos tumbado llevando la barra Z hacia la frente o coronilla para activar la cabeza larga y medial del tríceps.',
    },
    {
        'nombre': 'Elevaciones Laterales con Mancuernas',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'HOM',
        'dificultad': 'PRI',
        'equipo_necesario': 'Mancuernas',
        'definicion': 'Apertura lateral de brazos hasta la horizontal para generar amplitud y volumen en el deltoides lateral.',
    },
    {
        'nombre': 'Zancadas con Mancuernas (Lunges)',
        'tipo': 'LIB',
        'modalidad': 'REPS_PESO',
        'grupo_muscular': 'PIE',
        'dificultad': 'PRI',
        'equipo_necesario': 'Mancuernas',
        'definicion': 'Paso largo al frente flexionando ambas rodillas a 90 grados para hipertrofia unilateral de cuádriceps y glúteos con mejora de equilibrio.',
    },

    # =========================================================================
    # E. DEPORTES Y MOVILIDAD (TIPO: 'DEP', 'DAN', 'FLL')
    # =========================================================================
    {
        'nombre': 'Partido de Pádel',
        'tipo': 'DEP',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'FUL',
        'dificultad': 'PRI',
        'equipo_necesario': 'Pala de pádel y pelotas',
        'definicion': 'Partido individual o en parejas en pista reglamentaria. Alta exigencia anaeróbica con aceleraciones, frenadas bruscas, voleas y remates.',
    },
    {
        'nombre': 'Partido de Fútbol / Fútbol Sala',
        'tipo': 'DEP',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'FUL',
        'dificultad': 'PRI',
        'equipo_necesario': 'Balón de fútbol y calzado adecuado',
        'definicion': 'Partido competitivo con sprints intermitentes, cambios de dirección, regates y demanda cardiovascular completa.',
    },
    {
        'nombre': 'Partido de Baloncesto',
        'tipo': 'DEP',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'FUL',
        'dificultad': 'PRI',
        'equipo_necesario': 'Balón de baloncesto',
        'definicion': 'Sesión de juego continuo en cancha con saltos, desplazamientos laterales y lanzamientos a canasta.',
    },
    {
        'nombre': 'Danza Contemporánea',
        'tipo': 'DAN',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'FUL',
        'dificultad': 'INT',
        'equipo_necesario': 'Ropa cómoda / Esterilla opcional',
        'definicion': 'Expresión corporal, técnica de suelo, fluidez de movimiento y coreografía para flexibilidad, control del core y coordinación.',
    },
    {
        'nombre': 'Yoga y Movilidad Articular',
        'tipo': 'FLL',
        'modalidad': 'TIEMPO',
        'grupo_muscular': 'FUL',
        'dificultad': 'PRI',
        'equipo_necesario': 'Esterilla de yoga / Mat',
        'definicion': 'Secuencia de posturas, respiración diafragmática y elongación profunda para mejorar la flexibilidad, salud postural y rango articular.',
    },
]
