# Generated by Django 6.0.7 on 2026-07-28 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ejercicio')),
                ('definicion', models.TextField(verbose_name='Definición y técnica correcta')),
                ('tipo', models.CharField(choices=[('MAQ', 'Máquina'), ('LIB', 'Peso Libre'), ('CAL', 'Calistenia'), ('CAR', 'Cardio')], default='LIB', max_length=3, verbose_name='Tipo de Ejercicio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ejercicios/fotos/', verbose_name='Foto demostrativa')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Enlace al Vídeo (YouTube, Vimeo...)')),
                ('dificultad', models.CharField(choices=[('PRI', 'Principiante'), ('INT', 'Intermedio'), ('AVA', 'Avanzado')], default='PRI', max_length=3, verbose_name='Dificultad')),
                ('grupo_muscular', models.CharField(choices=[('PEC', 'Pectoral'), ('ESP', 'Espalda'), ('PIE', 'Piernas'), ('HOM', 'Hombros'), ('BRA', 'Brazos (Bíceps/Tríceps)'), ('COR', 'Core / Abdominales'), ('GLU', 'Glúteos')], max_length=3, verbose_name='Grupo Muscular Principal')),
                ('equipo_necesario', models.CharField(blank=True, help_text='Ej: Mancuernas, Banco inclinado, Polea...', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('series', models.PositiveIntegerField(default=3, verbose_name='Series')),
                ('repeticiones', models.PositiveIntegerField(default=10, verbose_name='Repeticiones por serie')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco si es Calistenia (peso corporal).', max_digits=5, null=True)),
                ('notas', models.TextField(blank=True, help_text="Ej: Me dolió un poco el hombro, o 'Subir peso la próxima vez'", null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ejercicios.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ejercicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ejercicio',
                'verbose_name_plural': 'Registros de Ejercicios',
                'ordering': ['-fecha'],
            },
        ),
    ]
