# Generated by Django 6.0.7 on 2026-07-29 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroejercicio',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='repeticiones',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='series',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='equipo_necesario',
            field=models.CharField(blank=True, help_text='Ej: Mancuernas, Polea...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace al Vídeo'),
        ),
        migrations.AlterField(
            model_name='registroejercicio',
            name='notas',
            field=models.TextField(blank=True, help_text='Ej: Sentí buena conexión mente-músculo.', null=True),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.PositiveIntegerField(help_text='Ej: 1, 2, 3...', verbose_name='Nº de Serie')),
                ('repeticiones', models.PositiveIntegerField(default=10, verbose_name='Repeticiones')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco si es Calistenia.', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_detalle', to='ejercicios.registroejercicio')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['numero_serie'],
            },
        ),
    ]
