# Generated by Django 6.0.7 on 2026-07-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_remove_registroejercicio_peso_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='numero_serie',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de Serie'),
        ),
    ]
