# Generated by Django 6.0.7 on 2026-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_alter_serie_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroejercicio',
            name='etiqueta',
            field=models.CharField(blank=True, help_text="Identificador opcional (ej. 'Mañana', 'Fuerza', 'Variante A')", max_length=50),
        ),
    ]
