# Generated by Django 6.0.7 on 2026-07-29 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_registroejercicio_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroejercicio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
