# Generated by Django 6.0.7 on 2026-09-19 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0005_registroejercicio_creado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_personalizados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='modalidad',
            field=models.CharField(choices=[('REPS_PESO', 'Repeticiones y Peso'), ('TIEMPO', 'Tiempo / Duración')], default='REPS_PESO', max_length=10, verbose_name='Modalidad de medición'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tiempo_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en segundos para ejercicios por tiempo.', null=True, verbose_name='Tiempo (segundos)'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='definicion',
            field=models.TextField(blank=True, default='', verbose_name='Definición y técnica correcta'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Ejercicio'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticiones',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Repeticiones'),
        ),
    ]
