# Generated by Django 6.0.7 on 2026-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0006_ejercicio_creado_por_ejercicio_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='equipo_necesario',
            field=models.CharField(blank=True, help_text='Ej: Mancuernas, Polea, Zapatillas de running, Pala de pádel...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(choices=[('PEC', 'Pectoral'), ('ESP', 'Espalda'), ('PIE', 'Piernas'), ('HOM', 'Hombros'), ('BRA', 'Brazos (Bíceps/Tríceps)'), ('COR', 'Core / Abdominales'), ('GLU', 'Glúteos'), ('FUL', 'Cuerpo Completo / Full Body'), ('CAR', 'Cardiovascular / Resistencia'), ('AGI', 'Agilidad y Coordinación')], max_length=3, verbose_name='Grupo Muscular Principal'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('MAQ', 'Máquina'), ('LIB', 'Peso Libre'), ('CAL', 'Calistenia'), ('CAR', 'Cardio'), ('DEP', 'Deporte (Pádel, Tenis, etc.)'), ('DAN', 'Danza / Baile'), ('OUT', 'Aire Libre / Outdoor'), ('FLL', 'Flexibilidad / Yoga / Movilidad')], default='LIB', max_length=3, verbose_name='Tipo de Ejercicio'),
        ),
    ]
