# Generated by Django 6.0.7 on 2026-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0009_catalogo_ejercicios_comunes'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia recorrida en kilómetros (ej. 5.2 para carrera).', max_digits=6, null=True, verbose_name='Distancia (km)'),
        ),
    ]
